import { Inter } from 'next/font/google';
import "./globals.css";
// import Header from '@/components/Header';
import Header from '../components/SharedComponents/Header';

import Footer from '../components/SharedComponents/Footer';
import MainFooter from '../components/SharedComponents/MainFooter';
import ConditionalPortfolio from '@/components/ConditionalPortfolio';




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Startup",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Header />
        <div className="flex-grow bg-[url('/icons/background-hp1bqckground.png')] bg-cover bg-no-repeat bg-top">
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
          <ConditionalPortfolio />
          <MainFooter />
        </div>
      </body>
    </html>
  );
}
